apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxx
  template:
    metadata:
      labels:
        app: nginxx
    spec:
      containers:
      - name: nginx
        image: nginx:service
        ports:
        - containerPort: 80
        - containerPort: 443