apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpresss
  template:
    metadata:
      labels:
        app: wordpresss
    spec:
      containers:
      - name:  wordpress
        image:  wordpress:service
        ports:
        - containerPort: 5050